AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: tapedeck-20210102

Resources:
  ArchiveLambda:
    Type: AWS::Lambda::Function
    Properties:
      Handler: index.handler
      Runtime: nodejs14.x
      InlineCode: "exports.handler = async (event, context) => { return 'hello world'; };"
      Description: Archive an m3u or mp3
      MemorySize: 512
      Timeout: 15
      Policies:
        - AWSConfigRulesExecutionRole
